apiVersion: 1

datasources:
  - name: accounting_es
    type: elasticsearch
    access: proxy
    database: "ngx_accounting-*"
    url: http://elasticsearch:9200
    jsonData:
      esVersion: "7.10.1"
      timeInterval: 1m
      timeField: "@timestamp"
